# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{em-proxy}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = %q{2010-10-03}
  s.description = %q{EventMachine Proxy DSL}
  s.email = %q{ilya@igvita.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/appserver.rb",
     "examples/beanstalkd_interceptor.rb",
     "examples/duplex.rb",
     "examples/line_interceptor.rb",
     "examples/port_forward.rb",
     "examples/relay_port_forward.rb",
     "examples/schemaless-mysql/mysql_interceptor.rb",
     "examples/selective_forward.rb",
     "examples/simple.rb",
     "examples/smtp_spam_filter.rb",
     "examples/smtp_whitelist.rb",
     "lib/em-proxy.rb",
     "lib/em-proxy/backend.rb",
     "lib/em-proxy/connection.rb",
     "lib/em-proxy/proxy.rb",
     "spec/helper.rb",
     "spec/proxy_spec.rb"
  ]
  s.homepage = %q{http://github.com/igrigorik/em-proxy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{em-proxy}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{EventMachine Proxy DSL}
  s.test_files = [
    "spec/helper.rb",
     "spec/proxy_spec.rb",
     "examples/appserver.rb",
     "examples/beanstalkd_interceptor.rb",
     "examples/duplex.rb",
     "examples/line_interceptor.rb",
     "examples/port_forward.rb",
     "examples/relay_port_forward.rb",
     "examples/schemaless-mysql/mysql_interceptor.rb",
     "examples/selective_forward.rb",
     "examples/simple.rb",
     "examples/smtp_spam_filter.rb",
     "examples/smtp_whitelist.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.9"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
  end
end

